name: Email Echo Test

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 21f3002924@ds.study.iitm.ac.in
        run: echo "Hello, world!"
